name: WebdriverIo + BrowserStack Mobile Automation

on:
  push:
    branches:
      - LQB-26
  pull_request:

jobs:
  wdio-run:
    runs-on: ubuntu-latest
    name: Automation Tests
    env:
      BS_USER: ${{ secrets.BS_USER }}
      BS_KEY: ${{ secrets.BS_KEY }}
      BS_APP_ID: ${{ secrets.BS_APP_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci


      - name: Run Wdio mobile tests using browserstack
        run:
          npm run wdio:run-all